import mongoose from "mongoose";

const PostSchema = new mongoose.Schema({
  prompt: {
    type: String,
    required: [true, "A post must have a promp"],
  },
  photo: {
    type: String,
    required: [true, "Post must have a photo generated by it"],
  },
  createdBy: {
    type: String,
    required: [true, "Post must belong to a user"],
  },
});

const Post = mongoose.model("Post", PostSchema);

export default Post;
